

server.servlet.contextPath=/colapp


spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp


logging.level.org.springframework=INFO
logging.level.com=INFO




spring.datasource.url=jdbc:oracle:thin:@localhost:1521:FREE
spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.datasource.username=colapp
spring.datasource.password=colapp

spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect


spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.enabled=true
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.platform: oracle


logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG

management.endpoints.web.exposure.include=*
management.endpoint.shutdown.enabled=true



#spring.datasource.umanagement.endpoints.web.exposure.include=*=jdbc:mariadb://localhost:3306/colapp?allowMultiQueries=true
#spring.datasource.username=colapp
#spring.datasource.password=secreto
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=create-drop



#server.port: 8443
#server.ssl.key-store: ./src/main/resources/cert/keystore.p12
#server.ssl.key-store-password: secreto
#server.ssl.keyStoreType: PKCS12
#server.ssl.keyAlias: tomcat

