CREATE TABLE Cervezas (
      id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
      nombre VARCHAR2(50),
      imagen VARCHAR2(200),
      alcohol FLOAT,
      color VARCHAR2(50),
      categoria VARCHAR2(200),
      descripcion VARCHAR2(1024),
      CONSTRAINT pk_cervezas PRIMARY KEY (id)
);


CREATE TABLE Usuarios (
  id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
  email VARCHAR2(200),
  password VARCHAR2(200),
  password_hash VARCHAR2(200),
  nombre VARCHAR2(200),
  rol VARCHAR2(64) DEFAULT 'USUARIO',
  CONSTRAINT pk_usuarios PRIMARY KEY (id)
);



CREATE TABLE Notas (
   id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
   creado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   titulo VARCHAR2(200),
   contenido VARCHAR2(200),
   publico NUMBER(1) DEFAULT NULL,
   usuarioid NUMBER(11) NOT NULL,
   cervezaid NUMBER(11) NOT NULL,
   CONSTRAINT pk_notas PRIMARY KEY (id),
   CONSTRAINT fk_usuarioid FOREIGN KEY (usuarioid) REFERENCES Usuarios(id),
   CONSTRAINT fk_cervezaid FOREIGN KEY (cervezaid) REFERENCES Cervezas(id)
);


CREATE OR REPLACE TRIGGER trg_calcular_password_hash
    BEFORE INSERT OR UPDATE ON Usuarios
    FOR EACH ROW
BEGIN
    :NEW.password_hash := LOWER(
            RAWTOHEX(
                    DBMS_CRYPTO.HASH(
                            UTL_RAW.CAST_TO_RAW(:NEW.password),
                            DBMS_CRYPTO.HASH_MD5
                    )
            )
                          );
END;
/
