CREATE USER colapp IDENTIFIED BY colapp;
GRANT ALL PRIVILEGES TO colapp;
GRANT EXECUTE ON DBMS_CRYPTO TO colapp;

CREATE TABLE colapp.Cervezas (
  id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR2(50),
  imagen VARCHAR2(200),
  alcohol FLOAT,
  color VARCHAR2(50),
  categoria VARCHAR2(200),
  descripcion VARCHAR2(1024),
  CONSTRAINT pk_cervezas PRIMARY KEY (id)
);


CREATE TABLE colapp.Usuarios (
  id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
  email VARCHAR2(200),
  password VARCHAR2(200),
  password_hash VARCHAR2(200),
  nombre VARCHAR2(200),
  rol VARCHAR2(64) DEFAULT 'USUARIO',
  CONSTRAINT pk_usuarios PRIMARY KEY (id)
);



CREATE TABLE colapp.Notas (
   id NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
   creado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   titulo VARCHAR2(200),
   contenido VARCHAR2(200),
   publico NUMBER(1) DEFAULT NULL,
   usuarioid NUMBER(11) NOT NULL,
   cervezaid NUMBER(11) NOT NULL,
   CONSTRAINT pk_notas PRIMARY KEY (id),
   CONSTRAINT fk_usuarioid FOREIGN KEY (usuarioid) REFERENCES colapp.Usuarios(id),
   CONSTRAINT fk_cervezaid FOREIGN KEY (cervezaid) REFERENCES colapp.Cervezas(id)
);


CREATE OR REPLACE TRIGGER colapp.trg_calcular_password_hash
    BEFORE INSERT OR UPDATE ON Usuarios
    FOR EACH ROW
BEGIN
    :NEW.password_hash := LOWER(
            RAWTOHEX(
                    DBMS_CRYPTO.HASH(
                            UTL_RAW.CAST_TO_RAW(:NEW.password),
                            DBMS_CRYPTO.HASH_MD5
                    )
            )
                          );
END;
/




INSERT INTO colapp.Usuarios (id, email, password, password_hash, nombre, rol) VALUES (1, 'administrador-colapp@jcyl.es', 'supersecreto', '', 'Administrador', 'ADMINISTRADOR');
INSERT INTO colapp.Usuarios (id, email, password, password_hash, nombre, rol) VALUES (2, 'TorGomRo@jcyl.es', 'TorGomRo', '', 'Roberto Torres', 'USUARIO');
INSERT INTO colapp.Usuarios (id, email, password, password_hash, nombre, rol) VALUES (3, 'NecSotGa@jcyl.es', 'NecSotGa', '', 'Gabriel Necedes', 'USUARIO');
INSERT INTO colapp.Usuarios (id, email, password, password_hash, nombre, rol) VALUES (4, 'LopGarIo@jcyl.es', 'LopGarIo', '', 'Iovani Lopez', 'USUARIO');


INSERT INTO colapp.cervezas VALUES (1,'Duvel','duvel.png',8.5,'Rubia','Strong Blond','Cerveza especial belga de alta fermentación, con segunda fermentación en botella. Aromas afrutados, evocando el olor a pera y manzana.');
INSERT INTO colapp.cervezas VALUES (2,'Chimay Triple','chimay_triple.png',8,'Rubia','Triple Trappist','La cerveza de Triple de Chimay es la más reciente de la abadía de un color dorado, la cerveza trapense combina el sabor dulce y amargo en un equilibrio poco común. ');
INSERT INTO colapp.cervezas VALUES (3,'Cornet','cornet.png',8.5,'Rubia','Strong Blond','De color dorado y sutil sabor a madera, refinado y peculiar. Sensación en boca como un vino de crianza roble. Con cuerpo, toque a roble, equilibrio entre la frutosidad de la levadura y la dulzura de la vainilla.');
INSERT INTO colapp.cervezas VALUES (4,'Montaraz','montaraz.png',5.3,'Rubia','Weizen-Weissbier','La primera creación de cervezas Montaraz, una cerveza rubia de trigo, suave, refrescante y con ligero aroma a plátano. Una cerveza artesana, elaborada en el Bierzo.');
INSERT INTO colapp.cervezas VALUES (5,'Ruda', 'ruda.jpg', 5.0, 'Tostada', 'Pale Ale' ,'Color ámbar y densa espuma, ligeramente amarga y notas dulces maltosas.');
INSERT INTO colapp.cervezas VALUES (6,'3 Cumbres', '3cumbres.png', 4.5, 'Rubia', 'Lager' ,'De color claro, es ligera, suave y muy refrescante que está elaborada siguiendo la Ley de la Pureza Alemana. Una cerveza ideal para cualquier momento y ocasión.');
INSERT INTO colapp.cervezas VALUES (7,'Berzaga', 'berzaga.jpg', 5.0, 'Tostada', 'Amber Ale' ,'Cerveza artesana tostada al estilo Inglés. Fácil de beber y baja carbonatación. Elaborada con una selección de cuatro maltas, muestra cierto dulzor inicial seguido de un sabor caramelizado que finaliza con toques tostados y un suave amargor en boca, fruto de los lúpulos balanceados en tiempo de cocción.');
INSERT INTO colapp.cervezas VALUES (8,'Tormenta Solar', 'baixer-tormenta-solar.jpg', 6.5 , 'Naranja pálido', 'Saison' ,'Cerveza de estilo Saison con auténtica levadura Saison. Estilo tipicamente belga de granja, en este caso con lúpulo neozelandés Nelson Sauvín, una combinación interesante de los sabores afrutados aportados por la levadura y los sabores y aromas tropicales y de vino blanco de este lúpulo, añadido en whirpool.');
INSERT INTO colapp.cervezas VALUES (9,'Perraborracha', 'perraborracha.png', 4.6 , 'Ambar', 'American Pale Ale' ,'American Pale Ale fresquita y sin complicaciones, amarga poco y es muy fácil de beber.');
INSERT INTO colapp.cervezas VALUES (10,'Barreno', 'barreno.png', 8.8 , 'Negra', 'Stout' ,'Cerveza negra, con aromas y sabor a café, regaliz, chocolate toque licoroso que da paso a ligero lúpulo. Cuerpo medio-completo. Amarga.');

INSERT INTO colapp.Notas (id, creado, titulo, contenido, publico, usuarioid, cervezaid)
VALUES (1, SYSTIMESTAMP, 'Bastante buena', 'Esta cerveza es una referencia.', 1, 1, 1);

COMMIT;
